---
title: "Tutorial of Trajectory Analysis of CyTOF data"
author: "Yuting Dai"
package: flowSpy
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Base_workflow}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r use-libs, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, 
                      warning = FALSE, message = TRUE)
```

This tutorial contains key steps of `flowSpy` workflow, including how to build an FSPY object, how to run dimensionality reduction and clustering, how to build a tree based on [Minimum Spanning Tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree) (MST) algorithm. 


``` {r quick-build, eval = FALSE}

# Loading packages
suppressMessages({
library(ggplot2)
library(LSD)
library(flowCore)
library(flowViz)
library(flowSpy)
})

#########################
# download sample
fcs.path <- "../../flowSpy-dataset/FCS/usecase1/"
fcs.file <- paste0(fcs.path, "FR-FCM-ZY9R-Bone_Marrow_cytof.fcs")

###########################################
# Get the expression matrix from FCS file
###########################################
# Solution 1
# Read FCS data via flowCore::read.FCS
# Expression data matrix from this method need to
# be performed compensation adjustment and transformation
# manually using flowCore
cytof.data <- flowCore::read.FCS(filename = fcs.file)
# show elements in mass cytometry data
cytof.data
# fetching expression data 
exp.data <- cytof.data@exprs

# Solution 2
# Read FCS data via flowSpy::runExprsExtract
# This solution is recommended
exp.data <- runExprsExtract(fcs.file, showDesc = FALSE, transformMethod = "autoLgcl")

# Fetching CD markers
markers <- colnames(exp.data)
markers.idx <- match(markers, colnames(exp.data))

# Build an FSPY object
# If you don't want to see the running log information, set verbose FALSE
# If there is only one case in your analysis workflow, you can just set stage "D0"
meta.data <- data.frame(cell = rownames(exp.data),
                        stage = "D0")
fspy <- createFSPY(raw.data = exp.data, markers = markers,
                   meta.data = meta.data,
                   normalization.method = "none",
                   verbose = T)

# Cluster cells by SOM algorithm
# Set random seed to make results reproducible
set.seed(6)
fspy <- runCluster(fspy, cluster.method = "som", xdim = 10, ydim = 10, verbose = T)

# Cluster based downsampling
# The total cell number is 236,187, and we can just keep 10% cells to reduce 
# computation load and improve computation time.
# Downsampling by setting downsampleing.size 0.1
set.seed(1)
fspy <- processingCluster(fspy, downsampling.size = 0.1)

# Now there is only 23,664 cells enrolled in the dimensionality reduction
fspy

# run Principal Component Analysis (PCA)
fspy <- runFastPCA(fspy, verbose = T)

# run t-Distributed Stochastic Neighbor Embedding (tSNE)
set.seed(1)
fspy <- runTSNE(fspy, dims = 2, verbose = T)

# run Diffusion map
fspy <- runDiffusionMap(fspy, verbose = T)

# run Uniform Manifold Approximation and Projection (UMAP)
fspy <- runUMAP(fspy, verbose = T)

# build minimum spanning tree based on tsne
fspy <- buildTree(fspy, dim.type = "tsne", dim.use = 1:2, verbose = T)

###########################################
# This is visualization module
###########################################

# Plot 2D tSNE. And cells are colored by cluster id
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "cluster.id", 
       alpha = 1, main = "tSNE", category = "categorical", show.cluser.id = T)

# Plot 2D tSNE. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD45RA", 
               main = "tSNE CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#00599F", "#EEEEEE", "#FF3222", "#FF3222"))

# Plot 2D UMAP. And cells are colored by cluster id
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "cluster.id", 
       alpha = 1, main = "UMAP", category = "categorical", show.cluser.id = T)

# Plot 2D UMAP. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "CD45RA", 
       main = "UMAP CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#00599F", "#EEEEEE", "#FF3222", "#FF3222"))

# Plot 3D UMAP. And cells are colored by CD45RA markers expression
plot3D(fspy, item.use = c("UMAP_1", "UMAP_2", "UMAP_3"), color.by = "CD45RA", 
       main = "UMAP CD45RA", category = "numeric", size = 0.2)

# Tree plot
plotTree(fspy, color.by = "cell.number", show.node.name = T, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotTree(fspy, color.by = "CD3", show.node.name = T, cex.size = 1, 
         as.tree = T, root.id = 25) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# plot Clusters 
plotCluster(fspy, item.use = c("PC_1", "PC_2"), category = "numeric",
            size = 10, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 100, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 100, color.by = "CD3", show.cluser.id = T) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))


# plot heatmap of cluster
plotClusterHeatmap(fspy)


##############################
### This part must be removed 
for (i in markers) {
p <- plotTree(fspy, color.by = i, show.node.name = F, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase1/marker.", i, ".pdf"), width = 6, height = 8)
}

for (i in markers) {
p <- plotTree(fspy, color.by = i, show.node.name = T, cex.size = 1, as.tree = T, root.id = 25) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase1/tree.", i, ".pdf"), width = 10, height = 8)
}

for (i in markers) {
p <- plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 100, color.by = i, main = i, show.cluser.id.size = 100) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase1/tsne.", i, ".pdf"), width = 6, height = 5)
}



######################## 
plotMarkerDensity(fspy)

plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "CD3", 
       alpha = 1, main = "PCA", category = "categorical", show.cluser.id = T) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

for (i in markers) {
p <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = i, 
       alpha = 1, main = i, category = "categorical", show.cluser.id = T) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase1/all.tsne.", i, ".pdf"), width = 6, height = 5)
}



######################## D3 network
library(plotly)
library(visNetwork)

visIgraph(fspy@network$mst, layout = "layout_in_circle")

visIgraph(fspy@network$mst, smooth = T) %>% visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE, manipulation = TRUE) %>% visLegend()

```














