---
title: "Time course flow cytometry data workflow"
author: "Yuting Dai"
package: flowSpy
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Time_course_workflow}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r use-libs, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, 
                      warning = FALSE, message = TRUE)
```

This tutorial contains key steps of `flowSpy` workflow, including how to build an FSPY object, how to run dimensionality reduction and clustering, how to build a tree based on [Minimum Spanning Tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree) (MST) algorithm. 


``` {r quick-build, eval = FALSE}

# Loading packages
suppressMessages({
library(ggplot2)
library(LSD)
library(flowCore)
library(flowViz)
library(flowSpy)
library(stringr)
})

#########################
# download sample
fcs.path <- "../../flowSpy-dataset/FCS/usecase2/"
fcs.files <- paste0(fcs.path, "D", c(0,2,4,6,8,10), "-sub.fcs")

set.seed(1)
fcs.data <- runExprsMerge(fcs.files, comp = F, transformMethod = "none", fixedNum = 2000)

# Refine colnames of fcs data
# for usecase 2
recol <- c(`FITC-A<NA>` = "CD43", `APC-A<NA>` = "CD34", `BV421-A<NA>` = "CD90",
           `BV510-A<NA>` = "CD45RA", `BV605-A<NA>` = "CD31", `BV650-A<NA>` = "CD49f",
           `BV 735-A<NA>` = "CD73", `PE-A<NA>` = "FLK1",
           `PE-Cy7-A<NA>` = "CD38")
colnames(fcs.data)[match(names(recol), colnames(fcs.data))] = recol

# Build an FSPY object
# If you don't want to see the running log information, set verbose FALSE
day.list <- c("D0", "D2", "D4", "D6", "D8", "D10")
meta.data <- data.frame(cell = rownames(fcs.data),
                        stage = str_replace(rownames(fcs.data), regex("-.+"), "") )
meta.data$stage <- factor(as.character(meta.data$stage), levels = day.list)

markers <- c("CD43", "CD34", "CD90", "CD45RA", "CD31", "CD49f", "CD73", "FLK1", "CD38")

fspy <- createFSPY(raw.data = fcs.data, markers = markers,
                   meta.data = meta.data,
                   normalization.method = "log",
                   verbose = T)

# Cluster cells by SOM algorithm
# Set random seed to make results reproducible
set.seed(3)
fspy <- runCluster(fspy, cluster.method = "som", xdim = 6, ydim = 6, verbose = T)

# Do not perform downsampling
set.seed(1)
fspy <- processingCluster(fspy, downsampling.size = 1, force.resample = F)

# run Principal Component Analysis (PCA)
fspy <- runFastPCA(fspy, verbose = T)

# run t-Distributed Stochastic Neighbor Embedding (tSNE)
set.seed(1)
fspy <- runTSNE(fspy, verbose = T)

# run Diffusion map
fspy <- runDiffusionMap(fspy, verbose = T)

# run Uniform Manifold Approximation and Projection (UMAP)
fspy <- runUMAP(fspy, verbose = T)

# build minimum spanning tree based on tsne
fspy <- buildTree(fspy, dim.type = "umap", dim.use = 1:2, verbose = T)

###########################################
# This is visualization module
###########################################

# Plot marker density
plotMarkerDensity(fspy)

# Plot 2D tSNE. And cells are colored by cluster id
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "cluster.id", 
       alpha = 1, main = "tSNE", category = "categorical", show.cluser.id = T)

# Plot 2D tSNE. And cells are colored by stage
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "stage", 
       alpha = 1, main = "tSNE", category = "categorical", show.cluser.id = T)

# Plot 2D tSNE. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD45RA", 
               main = "tSNE CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F","#00599F","#EEEEEE","#FF3222","#FF3222"))

# Plot 2D UMAP. And cells are colored by cluster id
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "cluster.id", 
       alpha = 1, main = "UMAP", category = "categorical", show.cluser.id = T)

# Plot 2D UMAP. And cells are colored by stage
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "stage", 
       alpha = 1, main = "UMAP", category = "categorical") +
   scale_color_manual(values = c("#00599F","#009900","#FF9933","#FF99FF","#7A06A0","#FF3222"))

# Plot 2D UMAPE. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "CD45RA", 
               main = "UMAP CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F","#00599F","#EEEEEE","#FF3222","#FF3222"))

# Tree plot
plotTree(fspy, color.by = "CD45RA", show.node.name = T, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotTree(fspy, color.by = "D0.percent", show.node.name = T, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# plot clusters
plotCluster(fspy, item.use = c("PC_1", "PC_2"), category = "numeric",
            size = 10, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 100, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# plot pie tree
plotPieTree(fspy, cex.size = 3, size.by.cell.number = T) + 
  scale_fill_manual(values = c("#00599F","#FF3222","#009900","#FF9933","#FF99FF","#7A06A0"))

plotPieTree(fspy, cex.size = 5, size.by.cell.number = T, as.tree = T, root.id = 18) + 
  scale_fill_manual(values = c("#00599F","#FF3222","#009900","#FF9933","#FF99FF","#7A06A0"))

# plot pie cluster
plotPieCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), cex.size = 40) + 
  scale_fill_manual(values = c("#00599F","#FF3222","#009900","#FF9933","#FF99FF","#7A06A0"))

plotPieCluster(fspy, item.use = c("PC_1", "PC_2"), cex.size = 0.5) + 
  scale_fill_manual(values = c("#00599F","#FF3222","#009900","#FF9933","#FF99FF","#7A06A0"))

# plot heatmap of cluster
plotClusterHeatmap(fspy)

# Violin plot
plotViolin(fspy, color.by = "cluster.id", marker = "CD45RA", text.angle = 90)

# plot cluster
plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), size = 10, show.cluser.id = T)

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD43", 
            size = 10, show.cluser.id = T, category = "numeric") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

###########################################
# This is pseudotime module
###########################################

fspy <- defRootCells(fspy, root.cells = c(18), verbose = T)

fspy <- runPseudotime(fspy, verbose = T, dim.type = "umap", dim.use = 1:2)

fspy <- defLeafCells(fspy, leaf.cells = c(25,24,33,1), verbose = T)

fspy <- runWalk(fspy, verbose = T)

###########################################
# This is visualization module
###########################################

# tSNE plot colored by pseudotime
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 1, color.by = "pseudotime") + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7A06A0"))

# UMAP plot colored by pseudotime
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), category = "numeric",
            size = 1, color.by = "pseudotime") + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7A06A0"))

# marker plot colored by pseudotime
plot2D(fspy, item.use = c("pseudotime", "CD43"), category = "categorical",
            size = 1, color.by = "stage")  + 
  scale_color_manual(values = c("#00599F","#009900","#FF9933","#FF99FF","#7A06A0","#FF3222"))

plot2D(fspy, item.use = c("pseudotime", "FLK1"), category = "categorical",
            size = 1, color.by = "stage")  + 
  scale_color_manual(values = c("#00599F","#009900","#FF9933","#FF99FF","#7A06A0","#FF3222"))

# Tree plot
plotTree(fspy, color.by = "pseudotime", cex.size = 1) + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7A06A0"))

# denisty plot by different stage
plotPseudotimeDensity(fspy, adjust = 1) + 
  scale_color_manual(values = c("#00599F","#009900","#FF9933","#FF99FF","#7A06A0","#FF3222"))

# trajectory value
plotPseudotimeTraj(fspy, var.cols = T) + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7A06A0"))

plotPseudotimeTraj(fspy, cutoff = 0.01, var.cols = T) + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7A06A0"))

plotHeatmap(fspy, downsize = 12000, cluster_rows = T,
            olor = colorRampPalette(c("blue","blue", "white","red","red"))(100))

# plot cluster
plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "traj.value.log", 
            size = 10, show.cluser.id = T, category = "numeric") + 
  scale_colour_gradientn(colors = c("#EEEEEE", "#FF3222", "#CC0000", "#CC0000"))

plotTree(fspy, color.by = "traj.value.log", cex.size = 1) + 
  scale_colour_gradientn(colors = c("#EEEEEE","#FF3222","#CC0000","#CC0000"))

###########################################
# fetching intermediate state cells
###########################################

cell.inter <- fetchCell(fspy, traj.value.log = 0.01)
sub.fspy <- subsetFSPY(fspy, cells = cell.inter)

set.seed(1)
sub.fspy <- runCluster(sub.fspy, cluster.method = "som", xdim = 1, ydim = 2, verbose = T)

# build minimum spanning tree based on raw
sub.fspy <- buildTree(sub.fspy, dim.type = "raw", verbose = T)

plotMarkerDensity(sub.fspy, adjust = 1)

plotPieTree(sub.fspy, cex.size = 0.5) + 
  scale_fill_manual(values = c("#00599F","#FF3222","#009900","#FF9933","#FF99FF","#7A06A0"))

##############################
### This part must be removed 
for (i in markers) {
p <- plotTree(fspy, color.by = i, show.node.name = F, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase2/marker.", i, ".pdf"), width = 6, height = 7)
}

for (i in markers) {
p <- plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = i, 
               main = i, category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase2/umap.", i, ".pdf"), width = 6, height = 5)
}


p <- plotTree(fspy, color.by = "CD45RA", show.node.name = T, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("../../flowSpy-dataset/Fig/usecase2/marker.n.CD45RA.pdf"), width = 6, height = 7)


plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), category = "categorical",
            size = 1, color.by = "stage")  + 
  scale_color_manual(values = c("#00599F","#009900","#FF9933","#FF99FF","#7A06A0","#FF3222"))


```














