---
title: "Tutorial of use case 1"
author: "Yuting Dai"
package: flowSpy
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Use Case 1}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r use-libs, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, 
                      warning = FALSE, message = TRUE)
```

This tutorial contains key steps of `flowSpy` workflow, including how to build an FSPY object, how to run dimensionality reduction and clustering, how to build a tree based on [Minimum Spanning Tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree) (MST) algorithm. 


``` {r quick-build, eval = FALSE}

# Loading packages
suppressMessages({
library(ggplot2)
library(LSD)
library(flowCore)
library(flowViz)
library(flowSpy)
})

#########################
# download sample
fcs.path <- "../../flowSpy-dataset/FCS/usecase1/"
fcs.file <- paste0(fcs.path, "20171103_U_01_1.fcs")

# Read flow cytomery data via flowCore::read.FCS
cytof.data <- flowCore::read.FCS(filename = fcs.file)

# show elements in mass cytometry data
cytof.data

# fetching expression data 
exp.data <- cytof.data@exprs

# rename colname of expression data
recol <- c(Y89Di = "CD45", Pr141Di = "CD49D",  Nd142Di = "CD11a", Nd143Di = "CD5",
           Nd144Di = "CD195", Nd145Di = "CD4", Nd146Di = "CD8a", Sm147Di = "CD7",
           Nd148Di = "CD16", Sm149Di = "CD25", Nd150Di = "CD134", Eu151Di = "CD2",
           Sm152Di = "CD95", Eu153Di = "CD366", Gd155Di = "CD279", Gd156Di = "CD183",
           Gd158Di = "CD194", Tb159Di = "CD197", Gd160Di = "CD28", Dy161Di = "CD152",
           Dy162Di = "CD69", Dy164Di = "CD161", Ho165Di = "CD45RO", Er166Di = "CD44",
           Er167Di = "CD27", Er168Di = "CD278", Tm169Di = "CD45RA", Er170Di = "CD3",
           Yb171Di = "CD9", Yb172Di = "CD57", Yb173Di = "CD137", Yb174Di = "HLA_DR",
           Lu175Di = "CD223", Yb176Di = "CD127")
colnames(exp.data)[match(names(recol), colnames(exp.data))] <- recol
markers <- as.character(recol)
markers.idx <- match(markers, colnames(exp.data))

# filtering cells with less 3 markers
exp.cells <- rowSums(exp.data[, markers.idx] > 0)
summary(exp.cells)
exp.data <- exp.data[which(exp.cells > 3), ]

# downsampling
cell.size <- 10000
set.seed(1)
exp.data.filter <- exp.data[sample(1:dim(exp.data)[1], cell.size), ]

# build an FSPY object
# if you don't want to see the running log information, set verbose FALSE
meta.data <- data.frame(cell = paste0("cell", 1:nrow(exp.data.filter)),
                        stage = "D0")
fspy <- createFSPY(raw.data = exp.data.filter, markers = markers,
                   meta.data = meta.data,
                   normalization.method = "log",
                   verbose = T)

# run KNN
fspy <- runKNN(fspy, knn = 30, verbose = T)

# run PCA
fspy <- runFastPCA(fspy, verbose = T)

# run tSNE
fspy <- runTSNE(fspy, verbose = T)

# run Diffusion map
fspy <- runDiffusionMap(fspy, verbose = T)

# run UMAP
fspy <- runUMAP(fspy, verbose = T)

# cluster cells by SOM algorithm
set.seed(1)
fspy <- runCluster(fspy, cluster.method = "som", xdim = 6, ydim = 6, verbose = T)
table(fspy@meta.data$cluster.id)

# calculation features of clusters
fspy <- processingCluster(fspy)

# build minimum spanning tree based on umap
fspy <- buildTree(fspy, dim.type = "tsne", dim.use = 1:2, verbose = T)

# define root cells
fspy <- defRootCells(fspy, root.cells = 25, verbose = T)

# pseudotime
fspy <- runPseudotime(fspy, verbose = T)

# define leaf cells
fspy <- defLeafCells(fspy, leaf.cells = 31, verbose = T)

# walk between root cells and leaf cells
fspy <- runWalk(fspy, verbose = T)


###############################
###       visualization     ###
###############################
library(ggpubr)

# tSNE
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "cluster.id", 
       alpha = 1, main = "PCA", category = "categorical", show.cluser.id = T)

plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "HLA_DR", 
               main = "HLA_DR", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

for (i in markers) {
p <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = i, 
               main = i, category = "numeric") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
ggsave(paste0("cytof.", i, ".pdf"), p, width = 6, height = 5)

}


p.03 <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD4", 
               main = "CD4", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
p.04 <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD8a", 
               main = "CD8a", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
p.05 <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD197", 
               main = "CD197", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
p.06 <- plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD45RA", 
               main = "CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))
p <- ggarrange(p.01, p.02, p.03, p.04, p.05, p.06, common.legend = TRUE,
               ncol = 2, nrow = 3)
ggsave("1.pdf", p, width = 8, height = 12)


plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "pseudotime", 
       alpha = 1, main = "PCA", category = "numeric", show.cluser.id = T)


# Diffusion Map
plot2D(fspy, item.use = c("DC_1", "DC_2"), color.by = "cluster.id", 
       alpha = 1, main = "Diffusion Map", category = "categorical", show.cluser.id = T)

# UMAP
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "cluster.id", 
       alpha = 1, main = "UMAP", category = "categorical", show.cluser.id = T)

plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "CD8a", 
       alpha = 1, main = "PCA", category = "numeric", show.cluser.id = T) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# Tree plot
plotTree(fspy, color.by = "CD4", show.node.name = T, cex.size = 1.5) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# Cluster plot
plotCluster(fspy, item.use = c("PC_1", "PC_2"), size = 10)

plotCluster(fspy, item.use = c("PC_1", "PC_2"), color.by = "pseudotime", 
            category = "numeric", size = 10)

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD8a", 
            category = "numeric", size = 10, show.cluser.id = T)

plotCluster(fspy, item.use = c("UMAP_1", "UMAP_2"), size = 10)

# Violin plot
plotViolin(fspy, color.by = "som.id", marker = "CD8a", text.angle = 90)

# marker density
plotMarkerDensity(fspy)

# Pseudotime trajectory
plotPseudotimeTraj(fspy, var.cols = T) + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7a06a0"))

# Pseudotime trajectory
plotPseudotimeTraj(fspy, cutoff = 0.1, var.cols = T) + 
  scale_colour_gradientn(colors = c("#F4D31D", "#FF3222","#7a06a0"))

# plot heatmap of cluster
plotClusterHeatmap(fspy)

# plot heatmap of cluster
plotHeatmap(fspy, cluster_rows = T)

```














