---
title: "Tutorial of use case 2 and 3"
author: "Yuting Dai"
package: flowSpy
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Use Case 2 and 3}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r use-libs, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, 
                      warning = FALSE, message = TRUE)
```

This tutorial contains key steps of `flowSpy` workflow, including how to build an FSPY object, how to run dimensionality reduction and clustering, how to build a tree based on [Minimum Spanning Tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree) (MST) algorithm. 


``` {r quick-build, eval = FALSE}

# Loading packages
suppressMessages({
library(ggplot2)
library(LSD)
library(flowCore)
library(flowViz)
library(flowSpy)
})

#########################
# download sample
fcs.path <- "../../flowSpy-dataset/FCS/usecase2-1/"
fcs.files <- paste0(fcs.path, "D", c(0,2,4,6,8,10), "-sub.fcs")

fcs.data <- runExprsMerge(fcs.files, comp = F, transformMethod = "none")

# Refine colnames of fcs data
recol <- c(`FITC-A<CD43>` = "CD43", `APC-A<CD34>` = "CD34", `BV421-A<CD90>` = "CD90",
           `BV510-A<CD45RA>` = "CD45RA", `BV605-A<CD31>` = "CD31", `BV650-A<CD49f>` = "CD49f",
           `BV 735-A<CD73>` = "CD73", `BV786-A<CD45>` = "CD45", `PE-A<FLK1>` = "FLK1",
           `PE-Cy7-A<CD38>` = "CD38")
colnames(fcs.data)[match(names(recol), colnames(fcs.data))] = recol


# Build an FSPY object
# If you don't want to see the running log information, set verbose FALSE
meta.data <- data.frame(cell = rownames(fcs.data),
                        stage = str_replace(rownames(fcs.data), regex("-.+"), "") )
meta.data$stage <- factor(as.character(meta.data$stage), levels = day.list)

markers <- c("CD43", "CD34", "CD90", "CD45RA", "CD31", "CD49f", "CD73", "CD45", "FLK1", "CD38")

fspy <- createFSPY(raw.data = fcs.data, markers = markers,
                   meta.data = meta.data,
                   normalization.method = "log",
                   verbose = T)

# Cluster cells by SOM algorithm
# Set random seed to make results reproducible
set.seed(1)
fspy <- runCluster(fspy, cluster.method = "som", xdim = 6, ydim = 6, verbose = T)

# Do not perform downsampling
fspy <- processingCluster(fspy, downsampleing.size = 1)

# Run KNN. This function is to find k-Nearest Neighbors for each cell
fspy <- runKNN(fspy, knn = 30, verbose = T)

# run Principal Component Analysis (PCA)
fspy <- runFastPCA(fspy, verbose = T)

# run t-Distributed Stochastic Neighbor Embedding (tSNE)
fspy <- runTSNE(fspy, verbose = T)

# run Diffusion map
fspy <- runDiffusionMap(fspy, verbose = T)

# run Uniform Manifold Approximation and Projection (UMAP)
fspy <- runUMAP(fspy, verbose = T)

# build minimum spanning tree based on tsne
fspy <- buildTree(fspy, dim.type = "tsne", dim.use = 1:2, verbose = T)


###########################################
# This is visualization module
###########################################

# Plot 2D tSNE. And cells are colored by cluster id
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "cluster.id", 
       alpha = 1, main = "tSNE", category = "categorical", show.cluser.id = T)

# Plot 2D tSNE. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), color.by = "CD45RA", 
               main = "tSNE CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#00599F", "#EEEEEE", "#FF3222", "#FF3222"))

# Plot 2D UMAP. And cells are colored by cluster id
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "cluster.id", 
       alpha = 1, main = "UMAP", category = "categorical", show.cluser.id = T)

# Plot 2D UMAPE. And cells are colored by CD45RA markers expression
plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), color.by = "CD45RA", 
               main = "UMAP CD45RA", category = "numeric")  + 
  scale_colour_gradientn(colors = c("#00599F", "#00599F", "#EEEEEE", "#FF3222", "#FF3222"))

# Tree plot
plotTree(fspy, color.by = "CD45RA", show.node.name = T, cex.size = 1) + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotCluster(fspy, item.use = c("PC_1", "PC_2"), category = "numeric",
            size = 10, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plotCluster(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 100, color.by = "CD45RA") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

# plot heatmap of cluster
plotClusterHeatmap(fspy)

# Violin plot
plotViolin(fspy, color.by = "cluster.id", marker = "CD45RA", text.angle = 90)

fspy <- defRootCells(fspy, root.cells = c(1), verbose = T)

fspy <- runPseudotime(fspy, verbose = T, dim.type = "none", dim.use = 1:2)

fspy <- defLeafCells(fspy, leaf.cells = c(32,26,27), verbose = T)

fspy <- runWalk(fspy, verbose = T)

plot2D(fspy, item.use = c("tSNE_1", "tSNE_2"), category = "numeric",
            size = 1, color.by = "pseudotime") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))

plot2D(fspy, item.use = c("UMAP_1", "UMAP_2"), category = "numeric",
            size = 1, color.by = "pseudotime") + 
  scale_colour_gradientn(colors = c("#00599F", "#EEEEEE", "#FF3222"))






#################################################

day = "D0"
fcs.data <- read.FCS(paste0("../../flowSpy-dataset/FCS/usecase2/", day, ".fcs"))

#fcs.data <- fcs.data[which(fcs.data[, "PerCP-Cy5-5-A"] < 150), ]
fcs.data <- fcs.data[which((fcs.data[, "FSC-A"] > 60000) & (fcs.data[, "FSC-A"] < 180000)), ]
fcs.data <- fcs.data[which((fcs.data[, "SSC-A"] > 30000) & (fcs.data[, "SSC-A"] < 150000)), ]
fcs.data <- fcs.data[which((fcs.data[, "FSC-H"] > 40000) & (fcs.data[, "FSC-H"] < 120000)), ]
fcs.data <- fcs.data[which((fcs.data[, "FSC-W"] > 60000) & (fcs.data[, "FSC-W"] < 120000)), ]
fcs.data <- fcs.data[which((fcs.data[, "SSC-H"] > 20000) & (fcs.data[, "SSC-H"] < 120000)), ]
fcs.data <- fcs.data[which((fcs.data[, "SSC-W"] > 60000) & (fcs.data[, "SSC-W"] < 110000)), ]
fcs.data <- fcs.data[which((fcs.data[, "FITC-A"] > -500) & (fcs.data[, "FITC-A"] < 500)), ]


fcs.data <- compensate(fcs.data, fcs.data@description$SPILL)
fcs.data.e <- fcs.data@exprs
pdf(paste0("../../flowSpy-dataset/Fig/usecase2/", day,".pdf"), width = 5.5, height = 6)
heatscatter(log10(abs(fcs.data.e[, "FITC-A"])+1), 
             log10(abs(fcs.data.e[, "BV421-A"])+1),
             cexplot = 0.3, main = "FCS in Day 0 after Gating and Filteration", 
             xlab = "CD43", ylab = "CD90",
             xlim = c(0,6), ylim = c(0,6))
dev.off()

write.FCS(fcs.data, paste0("../../flowSpy-dataset/FCS/usecase2/", day, "-sub.fcs"))
 
```














